### ISSUE TITLE
Create Project Wiki

### ISSUE THREAD

**Issue by ijoffe** [CMPUT301F23T20/JavaJeniuses#25]
Design a GitHub wiki to store project-related information

**Comment by donchuru** [comment]
Wiki looks sharp!

**Comment by tomaszayobahan** [comment]
Do you think we should add the Figma link to the UI storyboards section of the Wiki?

**Comment by donchuru** [comment]
Sure!

**Comment by tomaszayobahan** [comment]
Ok I will add it right now.

**Comment by tomaszayobahan** [comment]
Done
