### ISSUE TITLE
Choose Android Studio Template

### ISSUE THREAD

**Issue by KareemAssaf** [CMPUT301F23T20/JavaJeniuses#39]
Look over the android studio templates and choose the most suitable for this project

**Comment by ijoffe** [comment]
I think we should maybe start with the code for the last lab, I think it gives us a good starting point with the main activity and adding fragment. But I'm open to better ideas

What functionality do we want to start with? I assume basic add/edit/delete items and show item list?

**Comment by KareemAssaf** [comment]
Yeah we could do that, but I seen some of the templates and I feel like it could be better for this project like the 'Bottom Navigation View Activity' since we have that kind of template in our UI mockup.

For the functionality, I think yeah just getting the view for the list set up and the buttons like you said

**Comment by ijoffe** [comment]
We chose the NavBar template
