### ISSUE TITLE
Update Previous Submissions

### ISSUE THREAD

**Issue by ijoffe** [CMPUT301F23T20/JavaJeniuses#54]
Keep the submission for Part 2 up-to-date at the end of Part 3

**Comment by ijoffe** [comment]
I'll update the CRC Cards, but someone else more experienced with Figma should update the UI

**Comment by donchuru** [comment]
I've updated the add item, edit item, view item and filter features of the UI mockup

**Comment by donchuru** [comment]
I've updated the sort feature of our mockup

**Comment by ijoffe** [comment]
updated figma and crc, all good
